title: spiro-font
description: "Like a spirograph, for fonts: Change the parameters, make something pretty, and waste time."
baseurl: "/spiro-font"
url: "https://mccalluc.github.io"

# Build settings
theme: minima
plugins: []
collections:
  segmented:
    output: True
    permalink: /:collection/:name  # Default includes ".html" extension in url.
defaults:
  - scope:
      path: ''
      type: segmented
    values:
      layout: segmented

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude: []
