name: Portal CI

on: [push, pull_request]

jobs:
  build:

    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Node 14.1.0
      uses: actions/setup-node@v1
      with:
        node-version: '14.1.0'
   
    - name: Install node dependencies
      run: npm ci

    - name: Run test script
      run: ./test.sh
